// Auto-generated by tools/domewatch_calendar.py — do not edit by hand.
// Source: DomeWatch iCal, Office of the Democratic Whip (https://domewatch.us/ical)
window.CALENDAR_STATS = {
  "votingDaysHeld": 157,
  "votingDaysRemaining": 52,
  "votingDaysScheduled": 209,
  "votingDaysCanceled": 51,
  "nextVotingDay": "2026-06-23",
  "asOf": "2026-06-22",
  "generatedAt": "2026-06-22T18:02:48Z"
};
