// Auto-generated by tools/domewatch_floor.py — do not edit by hand.
// Source: DomeWatch, Office of the Democratic Whip (https://domewatch.us)
window.FLOOR_STATUS = {
  "inSession": false,
  "text": "House adjourned",
  "value": "house_not_in_session",
  "rollCall": {
    "number": "225",
    "question": "JOURNAL  - K 225 This is a test vote. K 225 This is a test vote. K 225 This is a test vote. K 225 This i"
  },
  "firstVotes": "First votes: Tuesday at 6:30 PM",
  "voteTotals": {
    "nays": "3",
    "not_voting": "423",
    "present": "2",
    "yeas": "3"
  },
  "sourceFetchedAt": "2026-06-22T13:56:51.424Z",
  "generatedAt": "2026-06-22T13:56:51Z"
};
