/* AUTO-GENERATED by build/generate_staff_summary.py — do not edit by hand */
/* Run: python3 build/generate_staff_summary.py  after adding a new member */

window.STAFF_COMP = {
  "cos": {
    "D": {
      "avg": 172891,
      "n": 6
    },
    "R": {
      "avg": 146666,
      "n": 5
    }
  },
  "ld": {
    "D": {
      "avg": 110375,
      "n": 5
    },
    "R": {
      "avg": 70088,
      "n": 5
    }
  },
  "cd": {
    "D": {
      "avg": 83381,
      "n": 6
    },
    "R": {
      "avg": 74168,
      "n": 4
    }
  },
  "sched": {
    "D": {
      "avg": 65416,
      "n": 4
    },
    "R": {
      "avg": 71298,
      "n": 4
    }
  }
};

window.STAFF_TENURE = {
  "cos": {
    "D": {
      "avg": 5.2,
      "n": 6
    },
    "R": {
      "avg": 6.2,
      "n": 5
    }
  },
  "ld": {
    "D": {
      "avg": 3.4,
      "n": 5
    },
    "R": {
      "avg": 5.4,
      "n": 5
    }
  },
  "cd": {
    "D": {
      "avg": 3.7,
      "n": 6
    },
    "R": {
      "avg": 2.2,
      "n": 4
    }
  },
  "sched": {
    "D": {
      "avg": 3.8,
      "n": 4
    },
    "R": {
      "avg": 5.5,
      "n": 4
    }
  }
};

window.ROLE_LABELS = {"cos": "Chief of Staff", "ld": "Legislative Director", "cd": "Communications Director", "sched": "Scheduler"};
