#!/usr/bin/env python3
"""Fetch live House floor status from the DomeWatch API and write floor-status.js.

DomeWatch (https://domewatch.us) is a public-data API from the Office of the
Democratic Whip. It exposes live floor activity, votes, and schedule. The API
sends NO CORS headers, so a static page can't call it from the browser. This
script runs server-side instead and bakes the result into floor-status.js,
which index.html loads same-origin (no key in the page, no CORS issue).

Usage:
  DOMEWATCH_API_KEY="$(tr -d '[:space:]' < .domewatch_key)" python3 tools/domewatch_floor.py
  # or, with no env var, it falls back to reading .domewatch_key directly.

The House is considered IN SESSION when now.value != "house_not_in_session".
"""
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

API_BASE = "https://data.domewatch.us/v1"
OUT_FILE = os.path.join(os.path.dirname(__file__), "..", "floor-status.js")
KEY_FILE = os.path.join(os.path.dirname(__file__), "..", ".domewatch_key")


def get_key():
    key = os.environ.get("DOMEWATCH_API_KEY", "").strip()
    if key:
        return key
    try:
        with open(KEY_FILE) as f:
            return f.read().strip()
    except FileNotFoundError:
        sys.exit("No API key: set DOMEWATCH_API_KEY or create .domewatch_key")


def fetch(path, key):
    req = urllib.request.Request(
        f"{API_BASE}{path}", headers={"X-API-Key": key, "Accept": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def main():
    key = get_key()
    floor = fetch("/floor", key)

    now = floor.get("now") or {}
    value = now.get("value") or ""
    in_session = bool(value) and value != "house_not_in_session"

    status = {
        "inSession": in_session,
        "text": now.get("text") or ("In Session" if in_session else "Adjourned"),
        "value": value,
        "rollCall": floor.get("roll_call") or None,
        "firstVotes": (floor.get("timeline") or {}).get("first_votes", {}).get("text"),
        "voteTotals": (floor.get("votes") or {}).get("counts", {}).get("totals"),
        "sourceFetchedAt": floor.get("fetchedAt"),
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    js = (
        "// Auto-generated by tools/domewatch_floor.py — do not edit by hand.\n"
        "// Source: DomeWatch, Office of the Democratic Whip (https://domewatch.us)\n"
        "window.FLOOR_STATUS = " + json.dumps(status, indent=2) + ";\n"
    )
    with open(OUT_FILE, "w") as f:
        f.write(js)

    print(f"Wrote {os.path.relpath(OUT_FILE)} — "
          f"{'IN SESSION' if in_session else 'not in session'} ({status['text']!r})")


if __name__ == "__main__":
    main()
