#!/usr/bin/env python3
"""Compute House floor voting-day stats from the DomeWatch iCal and write calendar-stats.js.

DomeWatch (https://domewatch.us) publishes the Office of the Democratic Whip's
official House floor schedule as an iCal feed at https://domewatch.us/ical. Unlike
the JSON API, the iCal endpoint needs NO API key. It still has no CORS headers,
so a static page can't fetch it from the browser — this script runs server-side
and bakes the derived figures into calendar-stats.js, which index.html loads
same-origin.

Events carry a CATEGORIES line we key off:
    VOTINGDAY / ADDEDVOTINGDAY   -> a scheduled floor voting day
    CANCELEDVOTINGDAY            -> a voting day later taken off the calendar
    FEDERALHOLIDAY / NONFEDERALHOLIDAY -> holidays/observances (ignored here)

"Held" vs "remaining" is relative to today (UTC date), so re-run to refresh.

Usage:
    python3 tools/domewatch_calendar.py            # write calendar-stats.js
    python3 tools/domewatch_calendar.py --dry-run  # print, write nothing
"""
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

ICAL_URL = "https://domewatch.us/ical"
OUT_FILE = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "calendar-stats.js"))

VOTING_CATS = {"VOTINGDAY", "ADDEDVOTINGDAY"}
CANCELED_CAT = "CANCELEDVOTINGDAY"


def fetch_ical():
    req = urllib.request.Request(ICAL_URL, headers={"User-Agent": "article-one/calendar"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def parse_events(raw):
    """Yield (yyyymmdd, category) for each VEVENT. Unfolds iCal line continuations."""
    text = raw.replace("\r\n", "\n").replace("\n\t", "").replace("\n ", "")
    for block in re.findall(r"BEGIN:VEVENT(.*?)END:VEVENT", text, re.S):
        def field(name):
            m = re.search(name + r"[^:]*:(.*)", block)
            return m.group(1).strip() if m else ""
        date = field("DTSTART")[:8]
        yield date, field("CATEGORIES")


def compute(raw, today):
    voting = sorted(d for d, c in parse_events(raw) if c in VOTING_CATS and len(d) == 8)
    canceled = [d for d, c in parse_events(raw) if c == CANCELED_CAT and len(d) == 8]
    held = [d for d in voting if d <= today]
    remaining = [d for d in voting if d > today]
    nxt = remaining[0] if remaining else None
    return {
        "votingDaysHeld": len(held),
        "votingDaysRemaining": len(remaining),
        "votingDaysScheduled": len(voting),
        "votingDaysCanceled": len(canceled),
        "nextVotingDay": (f"{nxt[:4]}-{nxt[4:6]}-{nxt[6:8]}" if nxt else None),
        "asOf": f"{today[:4]}-{today[4:6]}-{today[6:8]}",
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def main():
    dry = "--dry-run" in sys.argv[1:]
    today = datetime.now(timezone.utc).strftime("%Y%m%d")
    stats = compute(fetch_ical(), today)

    print(f"Voting days — held {stats['votingDaysHeld']}, remaining "
          f"{stats['votingDaysRemaining']}, canceled {stats['votingDaysCanceled']} "
          f"(of {stats['votingDaysScheduled']} scheduled). Next: {stats['nextVotingDay']}")

    if dry:
        print("--dry-run: not writing calendar-stats.js")
        return

    js = (
        "// Auto-generated by tools/domewatch_calendar.py — do not edit by hand.\n"
        "// Source: DomeWatch iCal, Office of the Democratic Whip (https://domewatch.us/ical)\n"
        "window.CALENDAR_STATS = " + json.dumps(stats, indent=2) + ";\n"
    )
    with open(OUT_FILE, "w") as f:
        f.write(js)
    print(f"Wrote {os.path.relpath(OUT_FILE)}")


if __name__ == "__main__":
    main()
